#!/usr/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks=32
#SBATCH --partition=phys.default.q
#SBATCH --output=job.out
#SBATCH --time=2:00:00
#SBATCH --mail-type=all
#SBATCH --constraint="local800G"
#SBATCH --mail-user=s.a.t.v.kraaij@student.tue.nl

module load gromacs/5.0.7

#gmx grompp -f minen.mdp -c conf.gro -p topol.top -o minen
#gmx mdrun -deffnm minen -nt 32 -ntmpi 32

#gmx grompp -f nvt.mdp -c minen.gro -p topol.top -o nvt
#gmx mdrun -deffnm nvt -nt 32 -ntmpi 32

gmx grompp -f npt.mdp -c npt_init.gro -p topol.top -o npt
gmx mdrun -deffnm npt -nt 32 -ntmpi 32






